# Generated by Django 5.0.7 on 2024-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(default='2024-01-18', verbose_name='Дата публикации'),
        ),
    ]
